{% set name = "corsikaio" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 173ae19bcfb026eef8c8b381abdb24c85559c3b928f48f06ad5e1675fb59644c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - pytest-runner
    - setuptools_scm
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - corsikaio
  commands:
    - python -c 'import corsikaio; print(corsikaio.__version__)' | grep -v 0.0.0

about:
  home: https://github.com/fact-project/pycorsikaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reader for corsika binary output files using numpy

  description: |
    Library for reading the CORSIKA binary output files into meaningful
    python data structures using numpy.
  doc_url: https://github.com/fact-project/pycorsikaio
  dev_url: https://github.com/fact-project/pycorsikaio

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
