{% set name = "corsikaio" %}
{% set version = "0.2.4.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f848172d08b925c974420928f945570c8f367cd4b8ff8e1cce45a1b044c4f454

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - pytest-runner
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - corsikaio

about:
  home: https://github.com/fact-project/pycorsikaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reader for corsika binary output files using numpy

  description: |
    Library for reading the CORSIKA binary output files into meaningful
    python data structures using numpy.
  doc_url: https://github.com/fact-project/pycorsikaio
  dev_url: https://github.com/fact-project/pycorsikaio

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
