{% set name = "corsikaio" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a8d7eb0b8c79f7ebdab543a98fa76235c2c8278cf6c129d906f44634a4e6a89

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - corsikaio
  commands:
    - python -c 'import corsikaio; print(corsikaio.__version__)' | grep -v 0.0.0

about:
  home: https://github.com/fact-project/pycorsikaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reader for corsika binary output files using numpy

  description: |
    Library for reading the CORSIKA binary output files into meaningful
    python data structures using numpy.
  doc_url: https://github.com/fact-project/pycorsikaio
  dev_url: https://github.com/fact-project/pycorsikaio

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
