{% set name = "corsikaio" %}
{% set version = "0.6.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c56171c4dbbb7b95a6f938dafa0cb9ecc996e508ed12906cbe07c8582f47e0f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - corsikaio
  commands:
    - python -c 'import corsikaio; print(corsikaio.__version__)' | grep -v 0.0.0

about:
  home: https://github.com/fact-project/pycorsikaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reader for corsika binary output files using numpy

  description: |
    Library for reading the CORSIKA binary output files into meaningful
    python data structures using numpy.
  doc_url: https://github.com/fact-project/pycorsikaio
  dev_url: https://github.com/fact-project/pycorsikaio

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
