{% set name = "corsikaio" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e1c27d6b5dba18a67a44fdb10f2749b9819b0059f5951292b0b37e9e58186b0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy
    - pytest-runner
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - corsikaio
  commands:
    - python -c 'import corsikaio; print(corsikaio.__version__)' | grep -v 0.0.0

about:
  home: https://github.com/fact-project/pycorsikaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reader for corsika binary output files using numpy

  description: |
    Library for reading the CORSIKA binary output files into meaningful
    python data structures using numpy.
  doc_url: https://github.com/fact-project/pycorsikaio
  dev_url: https://github.com/fact-project/pycorsikaio

extra:
  recipe-maintainers:
    - maxnoe
    - kosack
